### ISSUE TITLE
Less学习笔记

### ISSUE THREAD

**Issue by champkeh** [champkeh/blog#19]

**Comment by champkeh** [comment]
## 在Less中使用 clearfix 时需要这样用

```less
.clearfix {
    &::after {
        content: '';
        display: table;
        clear: both;
    }
    zoom: 1;
}
```

## 在Less中使用clearfix的另一种方式

```less
// 定义成一个mixin来使用
// 此时，在我们的css中，不会生成 .clearfix 这个类名
// 因此，在清理浮动的时候，我们也不需要给元素添加 clearfix 这个类，
// 只需要在less文件中需要的选择器中使用这个mixin就可以了
.clearfix () {
    &::after {
        content: '';
        display: table;
        clear: both;
    }
    zoom: 1;
}

// 假设我们要在class="content"这个元素是清除浮动
.content {
    .clearfix();
}
```
编辑结果为：
```css
.content {
    zoom: 1;
}
.content::after {
    content: '';
    display: table;
    clear: both;
}
```
